"""Initial migration

Revision ID: e81906ae1624
Revises: 
Create Date: 2026-06-22 11:17:00.817670

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e81906ae1624"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("clients",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("products",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("orders",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("client_id", sa.UUID(), nullable=False),
    sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["client_id"], ["clients.id"] ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("order_items",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("order_id", sa.UUID(), nullable=False),
    sa.Column("product_id", sa.UUID(), nullable=False),
    sa.Column("quantity", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["order_id"], ["orders.id"] ),
    sa.ForeignKeyConstraint(["product_id"], ["products.id"] ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("products")
    op.drop_table("clients")
    # ### end Alembic commands ###
